FROM ubuntu

COPY run.sh /run.sh

RUN apt update && \
    apt -y upgrade && \
    DEBIAN_FRONTEND=noninteractive apt -y install openssh-server iputils-ping traceroute iproute2 net-tools netcat dnsutils mc && \
    chmod +x /run.sh

CMD /run.sh ${ARG1} ${ARG2}
