FROM ubuntu

COPY run.sh /run.sh

RUN apt update && \
    apt -y upgrade && \
    apt -y install openssh-server iputils-ping traceroute iproute2 net-tools netcat dnsutils \
    chmod +x /run.sh

CMD /run.sh
